meta_product_name: "Gamilfex"
meta_title: "Gamiflex | Find your next game!"
meta_description: "The Netflix suggestion algorithm for Video Games"
meta_image: "http://res.cloudinary.com/dqyrzcfez/image/upload/v1521136788/homepage.png"
